{
 "title": "BuzzTalk monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "-", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Current Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{db=\"cpanel_username_buzztalk_mysql_db_dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Current Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_up{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Frontend Current Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://buzztalk.burava.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Current Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://buzztalk.burava.com/buzztalk-api/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media Current Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"http://buzztalk-api.burava.com/media/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most important info",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  label_join(\r\n    node_disk_info{},\r\n    \"intermediate_display\",\r\n    \" | \",\r\n    \"instance_name\",\r\n    \"public_ip\",\r\n    \"private_ip\",\r\n    \"instance_id\"\r\n  ),\r\n  \"display\",\r\n  \"GCP Instance: Name: $1 | IP: $2 (public) $3 (private) | ID: $4\",\r\n  \"intermediate_display\",\r\n  \"([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*)\"\r\n)",
     "legendFormat": "{{display}}"
    },
    {
     "expr": "label_replace(\r\n  label_join(\r\n    cpanel_info{},\r\n    \"intermediate_display\",\r\n    \" | \",\r\n    \"instance\",\r\n    \"public_ip\",\r\n    \"user\",\r\n    \"hostingpackage\"\r\n  ),\r\n  \"display\",\r\n  \"Namecheap server: $1\",\r\n  \"intermediate_display\",\r\n  \"(.*)\"\r\n)",
     "legendFormat": "{{display}}"
    },
    {
     "expr": "label_replace(\r\n  label_join(\r\n    cpanel_mysql_db_disk_usage{db=\"cpanel_username_buzztalk_mysql_db_dev\"},\r\n    \"intermediate_display\",\r\n    \" | \",\r\n    \"db\",\r\n    \"mysqlversion\"\r\n  ),\r\n  \"display\",\r\n  \"App DB: $1\",\r\n  \"intermediate_display\",\r\n  \"(.*)\"\r\n)",
     "legendFormat": "{{display}}"
    },
    {
     "expr": "label_replace(\r\n  label_join(\r\n    redis_instance_info{},\r\n    \"intermediate_display\",\r\n    \" | \",\r\n    \"redis_address\",\r\n    \"redis_version\",\r\n    \"redis_mode\",\r\n    \"maxmemory_policy\",\r\n    \"process_id\"\r\n  ),\r\n  \"display\",\r\n  \"Redis: Address: $1 | Version: $2 $3 | Eviction policy: $4 | Process: $5\",\r\n  \"intermediate_display\",\r\n  \"([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| (.*)\"\r\n)",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests & Response codes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by(response_code_class, backend_name) (stackdriver_https_lb_rule_loadbalancing_googleapis_com_https_request_count)",
       "legendFormat": "{{response_code_class}} {{backend_name}} "
      }
     ]
    },
    {
     "title": "Containers CPU usage | percent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"backend|frontend\"}[1m])\r\n/\r\nignoring (cpu, mode)\r\n(container_spec_cpu_quota{container_label_com_docker_swarm_service_name=~\"backend|frontend\"} / container_spec_cpu_period{container_label_com_docker_swarm_service_name=~\"backend|frontend\"})",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}} - {{instance}} {{public_ip}} ({{instance_id}}) "
      }
     ]
    },
    {
     "title": "Containers memory usage | percent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"backend|frontend\"} / container_spec_memory_limit_bytes{container_label_com_docker_swarm_service_name=~\"backend|frontend\"}",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}} ({{public_ip}}) {{container_label_com_docker_swarm_task_id}}"
      }
     ]
    },
    {
     "title": "Frontend Past Statuses",
     "type": "timeseries",
     "description": "Was frontend down in the past?\n\nThis concerns the whole service availability, not the particular docker service.",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "probe_success{instance=\"http://buzztalk.burava.com\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "App containers number | per instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 7, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by(container_label_com_docker_swarm_service_name, public_ip) (container_tasks_state{state=\"running\", container_label_com_docker_swarm_service_name=~\"backend|frontend\"})",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}} ({{public_ip}})"
      }
     ]
    },
    {
     "title": "Backend Past Statuses",
     "type": "timeseries",
     "description": "Was backend down in the past?\n\nThis concerns the whole service availability, not the particular docker service.",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "probe_success{instance=\"http://buzztalk.burava.com/buzztalk-api/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Google Cloud | Infra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of instances",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "stackdriver_instance_group_compute_googleapis_com_instance_group_size{}",
       "legendFormat": "{{instance_group_name}}"
      }
     ]
    },
    {
     "title": "Instance uptime",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 6, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_uptime_total{}",
       "legendFormat": "{{instance_name}} ({{instance_id}})"
      }
     ]
    },
    {
     "title": "Active containers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count by(container_label_com_docker_swarm_service_name) (container_tasks_state{state=\"running\", container_label_com_docker_swarm_service_name=~\"backend|cadvisor|frontend|node_exporter\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Instance CPU usage | percent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (avg by(instance, public_ip, instance_id) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
       "legendFormat": "{{instance}} {{public_ip}} ({{instance_id}}) "
      }
     ]
    },
    {
     "title": "Instance memory usage | percent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
       "legendFormat": "{{instance}} ({{public_ip}}) {{instance_id}} "
      }
     ]
    },
    {
     "title": "Instance Disk Space usage | percent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (node_filesystem_avail_bytes{instance=~\".*\", public_ip=~\".*\", instance_id=~\".*\", device!~\"'rootfs'\", mountpoint=\"/etc/hostname\"} / node_filesystem_size_bytes{instance=~\".*\", public_ip=~\".*\", instance_id=~\".*\", device!~\"'rootfs'\", mountpoint=\"/etc/hostname\"})",
       "legendFormat": "{{mountpoint}} {{instance}} ({{public_ip}}) {{instance_id}} "
      }
     ]
    },
    {
     "title": "Instance Inodes usage | percent",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1- (node_filesystem_files_free{instance=~\".*\", public_ip=~\".*\", instance_id=~\".*\", device!~\"'rootfs'\", mountpoint=\"/etc/hostname\"} / node_filesystem_files{instance=~\".*\", public_ip=~\".*\", instance_id=~\".*\", device!~\"'rootfs'\", mountpoint=\"/etc/hostname\"})",
       "legendFormat": "{{instance}} ({{public_ip}}) {{instance_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL version",
     "type": "stat",
     "description": "Go to Value options > Fields and choose the field to fix the panel",
     "gridPos": { "h": 3, "w": 12, "x": 6, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "cpanel_info{}", "legendFormat": "{{mysqlversion}}" }
     ]
    },
    {
     "title": "Database Past Statuses",
     "type": "timeseries",
     "description": "Was the database down in the past?",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "probe_success{db=\"cpanel_username_buzztalk_mysql_db_dev\"}",
       "legendFormat": "{{db}}"
      }
     ]
    },
    {
     "title": "MySQL disk usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cpanel_mysql_db_disk_usage{db=\"cpanel_username_buzztalk_mysql_db_dev\"}",
       "legendFormat": "{{db}} ({{user}}) {{shorthostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis info",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 6, "y": 743 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
     "targets": [
      {
       "expr": "label_replace(\r\n  label_join(\r\n    redis_instance_info{},\r\n    \"intermediate_display\",\r\n    \" | \",\r\n    \"redis_address\",\r\n    \"redis_version\",\r\n    \"redis_mode\",\r\n    \"maxmemory_policy\",\r\n    \"process_id\"\r\n  ),\r\n  \"display\",\r\n  \"Address: $1 | Version: $2 $3 | Eviction policy: $4 | Process: $5\",\r\n  \"intermediate_display\",\r\n  \"([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| (.*)\"\r\n)",
       "legendFormat": "display"
      }
     ]
    },
    {
     "title": "Redis Past Statuses",
     "type": "timeseries",
     "description": "Was Redis down in the past?",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 746 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      { "expr": "redis_up{}", "legendFormat": "redis_hostname" }
     ]
    },
    {
     "title": "Current Clients",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 9, "y": 746 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "redis_connected_clients{}", "legendFormat": "redis_hostname" }
     ]
    },
    {
     "title": "Clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 746 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "redis_connected_clients{}", "legendFormat": "redis_hostname" }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 754 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (redis_db_keys{}) by (db, instance)",
       "legendFormat": "redis_hostname {{ db }}"
      }
     ]
    },
    {
     "title": "CPU utilization total | percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 754 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(rate(redis_cpu_user_seconds_total{}[$__range]) + rate(redis_cpu_sys_seconds_total{}[$__range])) * 100",
       "legendFormat": "redis_hostname"
      }
     ]
    },
    {
     "title": "Average TTL / db",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 762 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "redis_db_avg_ttl_seconds{}", "legendFormat": "{{ db }}, redis_hostname" }
     ]
    },
    {
     "title": "Memory Usage | percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 762 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(100 * (redis_memory_used_bytes{}  / redis_memory_max_bytes{}))",
       "legendFormat": "redis_hostname"
      }
     ]
    },
    {
     "title": "Hits / Misses per Sec",
     "type": "timeseries",
     "description": "Hits: Number of requested files that were served from the cache without requesting to the backend\n\nMisses: Number of times a request was answered by the backend because the item was not cached",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 769 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total{}[5m])",
       "legendFormat": "hits, redis_hostname"
      },
      {
       "expr": "irate(redis_keyspace_misses_total{}[5m])",
       "legendFormat": "misses, redis_hostname"
      }
     ]
    },
    {
     "title": "Expired/Evicted Keys",
     "type": "timeseries",
     "description": "Each change on the panel represents the number of expired/evicted keys over the past 5 minutes for each Redis instance.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 770 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(redis_expired_keys_total{}[5m])) by (instance)",
       "legendFormat": "expired, redis_hostname"
      },
      {
       "expr": "sum(increase(redis_evicted_keys_total{}[5m])) by (instance)",
       "legendFormat": "evicted, redis_hostname"
      }
     ]
    },
    {
     "title": "Errors in Redis Exporter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 777 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_exporter_last_scrape_error{instance=\"127.0.0.1:9121\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namecheap server | BuzzTalk Critical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Account Information",
     "type": "stat",
     "description": "Go to Value options > Fields and choose the field to fix the panel",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
     "targets": [
      {
       "expr": "label_replace(\r\n  label_join(\r\n    cpanel_info{},\r\n    \"intermediate_display\",\r\n    \" | \",\r\n    \"operatingsystem\",\r\n    \"machinetype\",\r\n    \"cpanelversion\",\r\n    \"user\",\r\n    \"hostingpackage\",\r\n    \"public_ip\",\r\n    \"hostname\",\r\n    \"shorthostname\",\r\n    \"kernelversion\",\r\n    \"perlversion\",\r\n    \"mysqlversion\"\r\n  ),\r\n  \"display\",\r\n  \"OS: $1 $2 | cPanel version: $3 | cPanel user: $4 | Plan: $5 | Public IP: $6 | Hostname: $7 (short: $8) | Kernel: $9 | Perl: $10 | MySQL: $11\",\r\n  \"intermediate_display\",\r\n  \"([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| ([^|]*) \\\\| (.*)\"\r\n)\r\n",
       "legendFormat": "{{display}}"
      }
     ]
    },
    {
     "title": "FTP account disk space used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cpanel_ftp_account_disk_usage{ftp_account=\"somemediaaccount@buzztalk-api.burava.com\"}",
       "legendFormat": "{{ftp_account}} ({{user}}) {{shorthostname}}"
      }
     ]
    },
    {
     "title": "Media Past Statuses",
     "type": "timeseries",
     "description": "Was media endpoint down in the past?",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "targets": [
      {
       "expr": "probe_success{instance=\"http://buzztalk-api.burava.com/somemediaurl/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Email account disk space used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "cpanel_email_disk_usage{email=\"buzztalk@burava.com\"}",
       "legendFormat": "{{email}} ({{user}}) {{shorthostname}}"
      }
     ]
    },
    {
     "title": "CPU usage | Percent",
     "type": "timeseries",
     "description": "CPU Usage specifies how much of the allocated CPU resources you are currently using. The amount of CPU resources we provide to each account is the percentage of the server’s resources.\nIf CPU reaches 100% it means that your account is using all of the CPU resources allocated, and any new processes will be put to sleep until existing processes complete. This can cause your website to slow down dramatically and in extreme cases even time out.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpanel_cpu_percent{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Memory usage | Percent",
     "type": "timeseries",
     "description": "Physical Memory Usage (RAM) is the actual memory allocated for your account. Virtual memory is usually a file on a disk drive that the operating system uses to store information (swap-to-from) when the real memory becomes full, for instance, the page (swap) file on a Linux system. Therefore, if you try to publish a big post, it might take all physical memory to do so, but after some time it will be normalized.\n\nIf this value reaches the limit you may begin to experience PHP errors (if applicable) on your website, or in very extreme cases may see a CloudLinux error page. These errors are typically only brief and once the usage has reduced to below the limit, will automatically clear.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpanel_memphy_percent{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    }
   ]
  },
  {
   "title": "Namecheap server | Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk space | Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpanel_diskusage_percent{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Entry Processes",
     "type": "timeseries",
     "description": "Entry Processes is the number of processes that enter your account. It is also known as \"Apache concurrent connections\". This value defines how many PHP or CGI scripts you can run at a single time. For example, every PHP page that is accessed by a user will usually generate a single entry process. Many people misinterpret this value as “number of visitors you can have on your website at once”. Whilst it is true that each visitor accessing a PHP page will spawn an entry process, these processes usually end so quickly that it is extremely unlikely that 10 will be spawned concurrently and at a single moment unless you had a significantly large number of simultaneous visitors on your website at once.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_ep{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Processes count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "cpanel_nproc{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    },
    {
     "title": "Files usage | Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "cpanel_filesusage_percent{}", "legendFormat": "{{user}} ({{shorthostname}})" }
     ]
    }
   ]
  }
 ]
}